### ISSUE TITLE
Data Grid 8.9.2 requires useSyncExternalStore4 which is not available in React 17

### ISSUE THREAD

**Issue by Julian-Quirke** [mui/mui-x#19087]
### Steps to reproduce

Steps:
1. Open this link to live example: https://stackblitz.com/edit/qfmfuuxt-5karh66u
2. View console error: useSyncExternalStore4 is not a function

### Current behavior

Data Grid throws an error: useSyncExternalStore4 is not a function

### Expected behavior

Data Grid should load correctly

### Context

Data grid should work correctly with React 17 - as it does in 8.9.1

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.0 undefined
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: latest => 11.14.0 
    @emotion/styled: latest => 11.14.1 
    @mui/core-downloads-tracker:  7.3.1 
    @mui/material: latest => 7.3.1 
    @mui/material-pigment-css: ^7.3.1 => 7.3.1 
    @mui/private-theming:  5.17.1 
    @mui/styled-engine:  5.18.0 
    @mui/system: ^5.15.14 => 5.18.0 
    @mui/types:  7.4.5 
    @mui/utils:  7.3.1 
    @mui/x-data-grid: 8.9.2 => 8.9.2 
    @mui/x-internals:  8.9.2 
    @mui/x-virtualizer:  0.1.0 
    @pigment-css/react: ^0.0.30 => 0.0.30 
    @types/react: ^17.0.0 => 19.1.9 
    react: ^17.0.0 => 17.0.2 
    react-dom: ^17.0.0 => 17.0.2 
    typescript: latest => 5.9.2 
```
</details>

**Search keywords**: React 17 react@17 data grid 8.9.2

**Comment by MBilalShafi** [comment]
The issue has been fixed in https://github.com/mui/mui-x/pull/19063 and will be released in https://github.com/mui/mui-x/pull/19084 this week.
Please keep an eye on the release and update to fix the issue.
