### ISSUE TITLE
[data grid] Updates handled with `onRowSelectionModelChange` while using `treeData` results in an error

### ISSUE THREAD

**Issue by DoodleBobBuffPants** [mui/mui-x#14859]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/mui-datagrid-treedata-repro-ircjfa0?file=README.md,package.json

Steps:
1. Using sample component [here](https://mui.com/x/react-data-grid/tree-data/#gaps-in-the-tree)
2. Add some state for the selection model as in the live example linked above
3. Update the state in `onRowSelectionModelChange`
4. Upon rendering there is the error:
   ```
   Warning: Cannot update a component (`Repro`) while rendering a different component (`ForwardRef(DataGridPro)`). To locate the bad setState() call inside `ForwardRef(DataGridPro)`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at DataGridPro
    at div
    at Repro
   ```

### Current behavior

An error (well, a warning logged to `console.error`)

### Expected behavior

There shouldn't be an error

### Context

This fails in 7.19.0 but works in 7.18.0

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.0 undefined
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.13.3 => 11.13.3 
    @emotion/styled: 11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.1.2 
    @mui/material:  6.1.2 
    @mui/private-theming:  6.1.2 
    @mui/styled-engine:  6.1.2 
    @mui/system:  6.1.2 
    @mui/types:  7.2.17 
    @mui/utils:  6.1.2 
    @mui/x-data-grid:  7.19.0 
    @mui/x-data-grid-pro: 7.19.0 => 7.19.0 
    @mui/x-internals:  7.18.0 
    @mui/x-license:  7.18.0 
    @types/react:  18.3.11 
    react: 18.3.1 => 18.3.1 
    react-dom: 18.3.1 => 18.3.1 
```

Also fails on a Windows machine when run in an Electron app; the above is for the StackBlitz repro
</details>

**Search keywords**: DataGridPro treeData state error react
**Order ID**: 65425

**Comment by michelengelen** [comment]
It seems this is a bug with codesandbox and/or stackblitz... i cannot reproduce this locally.
There is another error when not using a `React.useState` that likely causes this to surface in the first place: 
```
Warning: React instrumentation encountered an error: TypeError: ie.patchConsoleForStrictMode is not a function
```
I did also try to isolate the bug by removing all `StyledEngineProvider` code and also the strict mode, but with no success on this.
This might be related to this PR: https://github.com/mui/material-ui/pull/43632
cc @siriwatknp

**Comment by DoodleBobBuffPants** [comment]
> i cannot reproduce this locally

As in the example renders fine in a browser for you locally, or the test in the linked example succeeds for you? I'd have thought the test would fail locally too...

**Comment by michelengelen** [comment]
I did not run the tests, but since the recent CI runs where not complaining I guess this is not surfacing there as well ...

**Comment by siriwatknp** [comment]
> It seems this is a bug with codesandbox and/or stackblitz... i cannot reproduce this locally. There is another error when not using a `React.useState` that likely causes this to surface in the first place:
> 
> ```
> Warning: React instrumentation encountered an error: TypeError: ie.patchConsoleForStrictMode is not a function
> ```
> 
> I did also try to isolate the bug by removing all `StyledEngineProvider` code and also the strict mode, but with no success on this. This might be related to this PR: [mui/material-ui#43632](https://github.com/mui/material-ui/pull/43632) cc @siriwatknp

I don't think that PR is related, there is no React related change in that PR.

**Comment by michelengelen** [comment]
Right @siriwatknp ... sry for the confusion. It must have been a recent change introduced in v7.19.0 of the grid. Running this with v7.18.0 works.

@arminmeh do you have any idea where that error comes from?

**Comment by arminmeh** [comment]
Could it be related to the changes in Automatic parent selection PR @MBilalShafi?

**Comment by MBilalShafi** [comment]
It seems like a side effect of #14677 

During the first render, when the `filteredRowsSet` event is fired as a result of the initial filter lookup computation, the `setRowSelectionModel` gets fired with the initial value `[]` again which sets the external state, but the initial render is still in progress at this point, React throws the error.

I tried a fix in #14909
