### ISSUE TITLE
[x-telemetry] Vite Unit Testing Warning After Upgrading @mui/x-data-grid-premium to v8.1.0

### ISSUE THREAD

**Issue by SundarSPN** [mui/mui-x#17607]
### Steps to reproduce

After upgrading @mui/x-data-grid-premium to v8.1.0, I'm encountering a warning in my Vite + Vitest unit tests:

[mui-x-telemetry] error Error: Cannot find module 'D:\frontend\node_modules\@mui\x-telemetry\esm\runtime\get-context' imported from D:\frontend\node_modules\@mui\x-telemetry\esm\runtime\sender.js

step 1 .  I upgraded the MUI-x-data-grid-premium from 7+ to 8.1.0
step 2. If i run the application it works fine
step 3. If i run testcase 'Yarn test' i am getting the below warning error

[mui-x-telemetry] error Error: Cannot find module 'D:\frontend\node_modules\@mui\x-telemetry\esm\runtime\get-context' imported from D:\frontend\node_modules\@mui\x-telemetry\esm\runtime\sender.js
at finalizeResolution (node:internal/modules/esm/resolve:275:11)
at moduleResolve (node:internal/modules/esm/resolve:932:10)
at defaultResolve (node:internal/modules/esm/resolve:1056:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
at ModuleLoader.#cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:546:36)
at TracingChannel.tracePromise (node:diagnostics_channel:344:14)
at ModuleLoader.import (node:internal/modules/esm/loader:545:21) {code: 'ERR_MODULE_NOT_FOUND',url: 'file:///D:/frontend/node_modules/@mui/x-telemetry/esm/runtime/get-context'}

Is this a known issue with @mui/x-data-grid@8.1.0

Any help or best practices for resolving this kind of issue would be appreciated.

### Current behavior

If i run testcase 'Yarn test' i am getting the below warning error

[mui-x-telemetry] error Error: Cannot find module 'D:\frontend\node_modules\@mui\x-telemetry\esm\runtime\get-context' imported from D:\frontend\node_modules\@mui\x-telemetry\esm\runtime\sender.js
at finalizeResolution (node:internal/modules/esm/resolve:275:11)
at moduleResolve (node:internal/modules/esm/resolve:932:10)
at defaultResolve (node:internal/modules/esm/resolve:1056:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
at ModuleLoader.#cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:546:36)
at TracingChannel.tracePromise (node:diagnostics_channel:344:14)
at ModuleLoader.import (node:internal/modules/esm/loader:545:21) {code: 'ERR_MODULE_NOT_FOUND',url: 'file:///D:/frontend/node_modules/@mui/x-telemetry/esm/runtime/get-context'}

### Expected behavior

All test cases should pass without this warning message

### Context

i tried to mocking it in vite.config.ts and tried to install mui-x-telemetry, but it doesn't work

export default defineConfig({
  resolve: {
    alias: {
      '@mui/x-telemetry/esm/runtime/get-context': path.resolve(__dirname, 'src/__mocks__/get-context.js'),
    },
  },
});

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 22.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.2 - C:\Program Files\nodejs\npm.CMD   
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (134.0.3124.72)
  npmPackages:
    @emotion/react: ^11.14.0 => 11.14.0
    @emotion/styled: ^11.14.0 => 11.14.0
    @mui/core-downloads-tracker:  7.0.2
    @mui/icons-material: ^7.0.0 => 7.0.2
    @mui/material: ^7.0.0 => 7.0.2
    @mui/private-theming:  7.0.2
    @mui/styled-engine:  7.0.2
    @mui/system: ^7.0.0 => 7.0.2
    @mui/types:  7.4.1
    @mui/utils:  7.0.2
    @mui/x-data-grid:  8.1.0
    @mui/x-data-grid-premium: 8.1.0 => 8.1.0
    @mui/x-data-grid-pro:  8.1.0
    @mui/x-internals:  8.0.0
    @mui/x-license: 8.0.0 => 8.0.0
    @mui/x-telemetry:  8.0.0
    @mui/x-tree-view: 8.1.0 => 8.1.0
    @types/react: ^19.0.12 => 19.1.2
    react: ^19.0.0 => 19.1.0
    react-dom: ^19.0.0 => 19.1.0
    typescript: ~5.8.2 => 5.8.3
```
</details>

**Search keywords**: Vite Unit Testing Warning After Upgrading @mui/x-data-grid to v8.1.0 – [mui-x-telemetry] Module Not Found

**Comment by michelengelen** [comment]
@hasdfa seems like this is directly related or a duplicate of https://github.com/mui/mui-x/issues/17587

Could you check that please?

**Comment by alexfauquette** [comment]
@SundarSPN The fix of the related issue got released under v8.3.1

Can you close the issue if it's fixed, or give us feedback if it's not?

**Comment by SundarSPN** [comment]
Hi Team, Let me try and confirm here in a few days, I was occupied with other stuff

**Comment by SundarSPN** [comment]
Hi Team,
I have tested it now, and I’m no longer seeing the 'x-telemetry' warning message during the execution of the Vitest unit tests.
Thank you all for your efforts!

**Comment by michelengelen** [comment]
> Hi Team,
> I have tested it now, and I’m no longer seeing the 'x-telemetry' warning message during the execution of the Vitest unit tests.
> Thank you all for your efforts!

Great to hear that! Thanks for getting back with an update on this! Feel free to contact us again if you need anything else or encounter another bug! 💪🏻🙏🏻
